### ISSUE TITLE
Please remove these files

### ISSUE THREAD

**Issue by reunono** [Montie68/KoalaRescue#2]
Hello, <br/> <br/>I'm the creator of the Infinite Runner Engine, and this repository is sharing all of the asset's contents. Unfortunately, this is against the asset store's terms and conditions, and you can't redistribute it publicly like that.Please remove these files from this repository within the next 24 hours, or make the repository private. <br/>After that delay Github will take that repo down. <br/> <br/>Thanks, <br/>Renaud

**Comment by Montie68** [comment]
Thank you for your input,

No malice was intended as this was put on GitHub for marking of an University assignment only. I’ll try to include my lecture to the repo.

Regards 

Geoff Newman 
Ph: 0408 031 233
